#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

// Reading .env file
try {
    $dotenv = new Dotenv\Dotenv(__DIR__);
    $dotenv->load();
} catch(\Exception $e) {
}

if(!isset($_ENV['THUMCNO_PATH'])) {
    $_ENV['THUMCNO_PATH'] = __DIR__;
}

$application = new Application();

foreach(glob(__DIR__.'/console/*.php') as $file) {
    require $file;
}

$application->run();